### ISSUE TITLE
[Assignment]  #1.2 - Visualization Critique Blog Post

### ISSUE THREAD

**Issue by joeyklee** [sva-dsi/2018-fall-course#1]
**Please submit part 1.2 of [week 1's assignment](https://github.com/sva-dsi/2018-fall-course/blob/master/week01/ASSIGNMENT01.md) below.** 

## Note:
- Here's a handy [gist template](https://gist.github.com/auremoser/9dcfac8163e7737e7b5f) to help you structure your assignment submission (you can find that link in the syllabus as well). 
- I've included an example below of what your assignment might look like in the comments below.

## Make sure to submit:
- [x] Your link to your visualization critique blog post

***

- [x] @zbordenet
- [x] @JishengChen
- [x] @raaycho
- [x] @catalinacipri
- [x] @rutvigupta
- [x] @danihernandezdesign
- [x] @mblumley
- [x] @loveisthemssg
- [x] @zachnarva
- [x] @jpanicola
- [x] @p7rathi
- [x] @corinnereynolds
- [x] @dshepardL
- [x] @umila2
- [x] @dskinn
- [x] @tsokolowski
- [x] @ytsai2
- [x] @kubo921118
- [x] @YUWEN95
- [x] @xialibabanan
- [x] @wenqizheng
- [x] @looful
- [x] @jdong5

**Comment by joeyklee** [comment]
## Joey Lee 

- Assignment 1.2 visualization critique blog post: https://gist.github.com/joeyklee/06ee25f0dee96c1620001fe58ae57f53

**Comment by catalinacipri** [comment]
*Assignment 1.2 visualization critique blog post*
https://gist.github.com/catalinacipri/96cd3394b365910a903c1ff3d44ccfd8

**Comment by zbordenet** [comment]
Blog post 1.2: https://zbdatavisualization.wordpress.com/2018/09/13/the-journey-begins/

**Comment by corinnereynolds** [comment]
Assignment 1.2 Visualization Critique Blog Post:
https://gist.github.com/corinnereynolds/eacc90f018f7b5df0c9899d2599dd91e

**Comment by dskinn** [comment]
Assignment 1.2: Visualization Critique
https://gist.github.com/dskinn/aa427532b790e7944307f8580f162e36

**Comment by wenqizheng** [comment]
Assignment 1.2: Visualization Critique:
https://gist.github.com/wenqizheng/11841b6e35af39087120d5a8528c951c

**Comment by p7rathi** [comment]
Assignment 1.2: Visualization Critique:
https://gist.github.com/p7rathi/4c6c4af560df43514da542c752cf16e7

**Comment by JishengChen** [comment]
https://gist.github.com/JishengChen/3b67de6ac84490832ab412968203baff

**Comment by loveisthemssg** [comment]
Assignment 1.2: Visualization Critique
https://joliejardin.cargocollective.com

**Comment by mblumley** [comment]
Assignment 1.2 visualization critique blog post: https://gist.github.com/mblumley/2a17b22f30afb7aec686f7efd6acc162

**Comment by kubo921118** [comment]
Assignment 1.2 visualization critique blog post: https://gist.github.com/kubo921118/9d75d714911783c258e8741a40948443

**Comment by raaycho** [comment]
https://www.tumblr.com/blog/metricdataviz

**Comment by ytsai2** [comment]
Assignment 1.2 visualization critique blog post: https://goo.gl/Zq4nx4

**Comment by joeyklee** [comment]
> Assignment 1.2: Visualization Critique
> https://joliejardin.cargocollective.com

Hey @loveisthemssg  - thanks for posting! I can't seem to access the site as it is private, is there a way you can share the post by chance? Thanks!

**Comment by joeyklee** [comment]
> https://www.tumblr.com/blog/metricdataviz

Hi @raaycho - thanks for your post. I can't seem to access your post without a login. Do you mind sending a public link to your blog post?  Thanks!

**Comment by joeyklee** [comment]
> Assignment 1.2 visualization critique blog post: https://gist.github.com/kubo921118/9d75d714911783c258e8741a40948443

Hi @kubo921118 ! For whatever reason it seems your blog post doesn't have any text. If you can track down what happened, that would be super. Thanks!

**Comment by joeyklee** [comment]
> Assignment 1.2: Visualization Critique:
> https://gist.github.com/p7rathi/4c6c4af560df43514da542c752cf16e7

Hey @p7rathi - Thanks for your post! It seems that your wordpress site isn't linked properly. If you can make sure the link is correct and/or works for non-logged in users that would be great. Thanks!

**Comment by loveisthemssg** [comment]
hey @joeyklee changed blog site to : jelynne.jardiniano.com 
password: datavizfa18

**Comment by jpanicola** [comment]
Assignment 1.2- Blog Post
https://gist.github.com/jpanicola/acc01f75883bb2839122160971cd0af9

**Comment by jdong5** [comment]
Assignment 1.2 visualization critique blog post:
https://wordpress.com/post/jaithesis.wordpress.com/203

**Comment by raaycho** [comment]
https://metricdataviz.tumblr.com

**Comment by joeyklee** [comment]
> jaithesis.wordpress.com/203

Just for future reference, your public facing wordpress url is: https://jaithesis.wordpress.com

**Comment by jdong5** [comment]
Hi Joey,

Thank you for letting me know!

Jai

**Comment by danihernandezdesign** [comment]
Assignment 1/2 Visualization Critique Blog Post: https://gist.github.com/danihernandezdesign/3188d8014f9b21b394c4843e9da37521

**Comment by YUWEN95** [comment]
Assignment 1.2 visualization critique blog post:
https://wordpress.com/post/wangyuwendotblog.wordpress.com/106

**Comment by xialibabanan** [comment]
Assignment 1.2 visualization critique blog post: https://xiananzhang.wordpress.com/2018/09/26/data-visualization-week-1-assignment%e2%80%8b-1/

**Comment by umila2** [comment]
(Gist) Link to Visualization Critique Blog Post:
https://gist.github.com/umila2/373bb124eea135d4dfe6d74acee9d45d.js

URL: usinghdata.wordpress.com/2018/09/25/the-journey-begins/
