### ISSUE TITLE
[Assignment] #3 (UPDATED) - blog post + p5.js/introduction to computational media 

### ISSUE THREAD

**Issue by joeyklee** [sva-dsi/2018-fall-course#12]
[**Week 3 Assignment (updated)**](https://github.com/sva-dsi/2018-fall-course/blob/master/week03/ASSIGNMENT03-UPDATED.md) : introduction to computational media

1. Short paragraph about computation and your research interests
2. Watch (and enjoy) Dan Shiffman as he introduces you to P5.js and your first programming experiences.  

Please drop your assignment links in the comments below. 

NOTE: We will revisit the R demo in which [we calculate our CO2 emissions](https://github.com/sva-dsi/2018-fall-course/blob/master/week03/ASSIGNMENT03.md) at a later date. For now, it is **not required** to complete the exercise. By all means if you're curious and able, feel free to go through those materials. 

***

- [x] @zbordenet
- [x] @JishengChen
- [x] @raaycho
- [x] @catalinacipri
- [x] @rutvigupta
- [x] @danihernandezdesign
- [x] @mblumley
- [x] @loveisthemssg
- [x] @zachnarva
- [x] @jpanicola
- [x] @corinnereynolds
- [x] @dshepardL
- [x] @umila2
- [x] @dskinn
- [x] @tsokolowski
- [x] @ytsai2
- [x] @YUWEN95
- [x] @xialibabanan
- [x] @wenqizheng
- [x] @looful
- [x] @jdong5 

## Missing
- [ ] @kubo921118
- [ ] @p7rathi

**Comment by catalinacipri** [comment]
https://gist.github.com/catalinacipri/3870b9788c01e7e7662dd5b7ffe99288

**Comment by rutvigupta** [comment]
Rutvi's blog: https://gist.github.com/rutvigupta/7e2f73014bdfda001b7646c68ba97df6

**Comment by YUWEN95** [comment]
https://gist.github.com/YUWEN95/1ef163c1ad284887bb1e89bbc64036aa

**Comment by raaycho** [comment]
https://metricdataviz.tumblr.com/post/178500495024/092618-how-does-computation-and-data

**Comment by tsokolowski** [comment]
https://gist.github.com/tsokolowski/f52091a2a94800aee0399e59471ccb2b

**Comment by ytsai2** [comment]
https://gist.github.com/ytsai2/7dd7f09751b4954ff5353401241f6626

**Comment by wenqizheng** [comment]
https://thoughtfulpersondinosaur.tumblr.com/post/178513616889/week3-how-does-computation-and-data-visualization

**Comment by wenqizheng** [comment]
https://wenqiz.tumblr.com/post/178513616889/week3-how-does-computation-and-data-visualization

**Comment by zachnarva** [comment]
https://gist.github.com/zachnarva/7b308c5be00b548ae28183e3a973a245

**Comment by danihernandezdesign** [comment]
https://gist.github.com/danihernandezdesign/b6b1988f7c5bcc88b6513bf081c2d0b5

**Comment by loveisthemssg** [comment]
http://jelynne.jardiniano.com
password: joey

**Comment by looful** [comment]
https://gist.github.com/looful/dd4881d3320d4b085421e9144da97b75

**Comment by zbordenet** [comment]
https://wordpress.com/post/zbdatavisualization.wordpress.com/26

**Comment by zbordenet** [comment]
https://zbdatavisualization.wordpress.com/2018/09/27/computational-media/

**Comment by mblumley** [comment]
https://gist.github.com/mblumley/c1e7f9cd7dacfbb964fe5269a15c0e0b

**Comment by loveisthemssg** [comment]
> http://jelynne.jardiniano.com
> password: joey

http://jelynne.jardiniano.com/assignment-03-updated-introduction-to-computational-media

**Comment by dshepardL** [comment]
http://dsheparddataviz.data.blog/2018/09/28/data-visualization-the-new-matriarchy/

**Comment by dskinn** [comment]
https://gist.github.com/dskinn/677ba6933a554d4b2eef12e73dc0e5ba

**Comment by jdong5** [comment]
https://wordpress.com/post/jaithesis.wordpress.com/215

**Comment by xialibabanan** [comment]
https://github.com/xialibabanan/dsi-datavis-3/blob/master/README.md

**Comment by joeyklee** [comment]
Submissions now closed

**Comment by p7rathi** [comment]
https://gist.github.com/p7rathi/0d3a8f9488dd9ffa70276073907dab51

**Comment by kubo921118** [comment]
https://gist.github.com/kubo921118/9d75d714911783c258e8741a40948443
