### ISSUE TITLE
[Assignment] #4: Composition I

### ISSUE THREAD

**Issue by joeyklee** [sva-dsi/2018-fall-course#15]
Hi All! Please submit your assignments in the comments below! Thanks! 

***

- [x] @zbordenet
- [x] @JishengChen
- [x] @raaycho
- [x] @catalinacipri
- [x] @rutvigupta
- [x] @danihernandezdesign
- [x] @mblumley
- [x] @loveisthemssg
- [x] @zachnarva
- [x] @jpanicola
- [x] @p7rathi
- [x] @corinnereynolds
- [x] @dshepardL
- [x] @umila2
- [x] @dskinn
- [x] @tsokolowski
- [x] @ytsai2 
- [x] @YUWEN95
- [x] @xialibabanan
- [x] @wenqizheng
- [x] @looful
- [x] @jdong5 

## Missing

- [ ] @kubo921118

**Comment by dshepardL** [comment]
El Lisitisky, Option 2: 
<iframe src="https://editor.p5js.org/embed/Bkowkn0tX"></iframe>
(Two pieces I couldn't figure out - how to match the background color to the original image & how to get rid of the lines in the smaller rectangular shape. I noted this in the code)

Remix: <iframe src="https://editor.p5js.org/embed/rJC-2i0KQ"></iframe>

**Comment by catalinacipri** [comment]
4.1 My version of El Lissitzky https://editor.p5js.org/catalina/sketches/rkPchgjt7


4.2 My interative mix of El Lissitzky https://editor.p5js.org/catalina/sketches/r17pG5GqQ

**Comment by zbordenet** [comment]
4.1: https://editor.p5js.org/zbordenet/sketches/ry0a2eiF7
4.2: https://editor.p5js.org/zbordenet/sketches/HJgAANz97

**Comment by zachnarva** [comment]
4.1 [Static Version](https://editor.p5js.org/znarva/sketches/BymsUTzc7)

4.2 [Animated Version](https://editor.p5js.org/znarva/sketches/rk5oTesKX)

**Comment by tsokolowski** [comment]
4.1: https://editor.p5js.org/tsokolowski/sketches/HkgJ2lEf97

4.2: https://editor.p5js.org/tsokolowski/sketches/S1TVMTf5m

**Comment by raaycho** [comment]
4.1 https://editor.p5js.org/raaycho/sketches/Hyz5SlsF7
4.2 https://editor.p5js.org/raaycho/sketches/HJkuFhf5m

**Comment by JishengChen** [comment]
4.1: https://editor.p5js.org/jchen56@sva.edu/sketches/BJctXVsK7
4.2: https://editor.p5js.org/jchen56@sva.edu/sketches/HkVt5SQ9m (Drag the red circle!)

**Comment by corinnereynolds** [comment]
[Static version](https://editor.p5js.org/corinnereynolds/sketches/B1zxYUTY7)
[Animated version ](https://editor.p5js.org/corinnereynolds/sketches/HyuJfnb97)

**Comment by mblumley** [comment]
4.1  https://editor.p5js.org/mlumley/sketches/rk3VogoYQ
4.2  https://editor.p5js.org/mlumley/sketches/Byh_ThXq7

**Comment by p7rathi** [comment]
4.1 https://editor.p5js.org/prats2807/sketches/Hk4Dpxjt7 (Static)
4.2 https://editor.p5js.org/prats2807/sketches/BJpWKpm57 (Interactive)

**Comment by loveisthemssg** [comment]
4.1 Copy: https://editor.p5js.org/jmorse2@sva.edu/sketches/H1Q-3ym5X
4.2 Remix: https://editor.p5js.org/jmorse2@sva.edu/sketches/HknISkN9X

**Comment by jpanicola** [comment]
Static: https://editor.p5js.org/full/HJf-plsY7
Animated: https://editor.p5js.org/full/rkMdng4c7

**Comment by ytsai2** [comment]
4.1 https://editor.p5js.org/full/S1v_rejKX
4.2 https://editor.p5js.org/full/HJhrOmN97

**Comment by looful** [comment]
[Boring, static version](https://editor.p5js.org/full/H1ZpdjLcQ)
[REEEEEMIX](https://editor.p5js.org/full/H1W146wc7)

**Comment by danihernandezdesign** [comment]
https://editor.p5js.org/full/H13anlsYQ

**Comment by wenqizheng** [comment]
4.1 https://editor.p5js.org/wenqizheng/sketches/S1h1K6Xq7
4.2 https://editor.p5js.org/wenqizheng/sketches/SyT3dWVcm

**Comment by rutvigupta** [comment]
4.1 [](https://editor.p5js.org/rutvigupta/sketches/Hk3Vy429m)
4.2 [](https://editor.p5js.org/rutvigupta/sketches/rJMNJU2qm)

**Comment by dskinn** [comment]
4.1 https://editor.p5js.org/dskinn/sketches/BkbY2vC9X
4.2 https://editor.p5js.org/dskinn/sketches/B1ndArR5X

**Comment by umila2** [comment]
4.1 https://editor.p5js.org/usingh/sketches/HyXDxq-s7
4.2 https://editor.p5js.org/full/HyKv4QNsm

**Comment by xialibabanan** [comment]
4.1 https://editor.p5js.org/jdong5/sketches/rydmlGroX
4.2 https://editor.p5js.org/xzhang26@sva.edu/sketches/r1NBE5BoQ

**Comment by xialibabanan** [comment]
4.1 https://editor.p5js.org/xzhang9213@gmail.com/sketches/HJTz44UjQ

**Comment by xialibabanan** [comment]
4.2 https://editor.p5js.org/xzhang26@sva.edu/full/r1NBE5BoQ

**Comment by xialibabanan** [comment]
https://wordpress.com/post/xiananzhang.wordpress.com/164

**Comment by YUWEN95** [comment]
4.1 https://editor.p5js.org/YUWEN95/sketches/HJU406Ge4
4.2 https://editor.p5js.org/YUWEN95/sketches/rkzqxCMlE

**Comment by joeyklee** [comment]
Submissions now closed

**Comment by kubo921118** [comment]
4.1 https://editor.p5js.org/kubo921118/sketches/Bo4sAqtzw
4.2 https://editor.p5js.org/kubo921118/sketches/ZUzHN26sw
