### ISSUE TITLE
[Assignment] #6: Life Expectancy Visualization

### ISSUE THREAD

**Issue by joeyklee** [sva-dsi/2018-fall-course#17]
Hi All! Please submit the links to your blog posts and visualizations below. 

NOTE: I've added an update to the assignment to reflect what we discussed in class - https://github.com/sva-dsi/2018-fall-course/blob/master/week06/ASSIGNMENT06.md#update-oct-12-2018

TLDR:

- Use the code in the example located here: https://github.com/sva-dsi/2018-fall-course/tree/master/examples/life-expectancy-1/process 
- style the interface and create more useful, intriguing, or alluring visual encodings to the data
- use metaphors that might draw attention to the data being collected? What comes to mind when comparing life expectencies? (e.g. tree rings, tallies, colors, etc); 

Thanks all! 

***

- [x] @zbordenet
- [x] @JishengChen
- [x] @raaycho
- [x] @catalinacipri
- [x] @rutvigupta
- [x] @danihernandezdesign
- [x] @mblumley
- [x] @zachnarva
- [x] @jpanicola
- [x] @p7rathi
- [x] @corinnereynolds
- [x] @dshepardL
- [x] @umila2
- [x] @dskinn
- [x] @tsokolowski
- [x] @ytsai2 
- [x] @YUWEN95
- [x] @xialibabanan
- [x] @wenqizheng
- [x] @jdong5

## Missing
- [ ] @looful
- [ ] @loveisthemssg
- [ ] @kubo921118

**Comment by catalinacipri** [comment]
https://gist.github.com/catalinacipri/5d35e0053e99e985392b0b4f1ba61817

**Comment by zachnarva** [comment]
https://gist.github.com/zachnarva/81d82911996ef439784a9fe5df56ae0d

**Comment by danihernandezdesign** [comment]
https://gist.github.com/danihernandezdesign/119089cca669528b62e420d0f4271b9e

**Comment by dshepardL** [comment]
https://editor.p5js.org/full/rJUHGupc7 😎
https://dsheparddataviz.data.blog/

**Comment by mblumley** [comment]
https://editor.p5js.org/mlumley/sketches/By1Xdn7oX
blog: https://gist.github.com/mblumley/620e5038935f6653f7e7f250d61273a8

**Comment by corinnereynolds** [comment]
visual: https://editor.p5js.org/corinnereynolds/sketches/SyxyQ_rim
blog: https://gist.github.com/corinnereynolds/3c779952e97b94d964b8c452059582d1
 🌈✌🏼🚃

**Comment by rutvigupta** [comment]
Visual: https://editor.p5js.org/rutvigupta/full/Sk_cVaEsm
Blog: https://gist.github.com/rutvigupta/bc84facef59205d185789813f78b62ad.js

**Comment by zbordenet** [comment]
Visual: https://editor.p5js.org/zbordenet/sketches/Bk53rBIiQ
Blog: https://zbdatavisualization.wordpress.com/2018/10/18/life-expectancy-viz/

**Comment by ytsai2** [comment]
https://editor.p5js.org/dataviz.yt/sketches/rkrEueToQ

**Comment by raaycho** [comment]
Visual: https://editor.p5js.org/raaycho/sketches/S196NY8sX
Blog: https://metricdataviz.tumblr.com/post/179406328884/life-expectancy-vis

**Comment by wenqizheng** [comment]
https://editor.p5js.org/wenqizheng/sketches/B1y7J88sX
https://gist.github.com/wenqizheng/73bf0cab87452a860b0d9797833d6ebf

**Comment by dskinn** [comment]
Blog: https://gist.github.com/dskinn/e021026c4039884749d66828af779631
Visual: https://editor.p5js.org/dskinn/sketches/SyrSoTOn7

**Comment by JishengChen** [comment]
Visual: https://editor.p5js.org/jchen56@sva.edu/sketches/S1KxJEAo7
Blog:  https://gist.github.com/JishengChen/91febd704ae0c81f0dc03c98ed3fd90d

**Comment by xialibabanan** [comment]
Visual: https://editor.p5js.org

**Comment by xialibabanan** [comment]
Work: https://editor.p5js.org/xzhang9213@gmail.com/full/BJPenoQ1N
Blog: https://xiananzhang.wordpress.com/2018/12/14/data-assignment-6-life-expectancy-visualization/

**Comment by jdong5** [comment]
Visual: https://editor.p5js.org/jdong5/sketches/rkQSjsSJV
Blog: https://jaithesis.wordpress.com/2018/11/01/reflection-on-assignment-6-life-expectancy-1/

**Comment by p7rathi** [comment]
https://editor.p5js.org/prats2807/sketches/HJDWKZHaQ

**Comment by jpanicola** [comment]
Visual: https://editor.p5js.org/jpanicola/sketches/HyksxIj1V
Blog: https://gist.github.com/jpanicola/61c8f6c75ab697fe9ddc972f1d383267

**Comment by tsokolowski** [comment]
Sketch: https://editor.p5js.org/tsokolowski/sketches/SkpyOgF2Q
Blog: https://gist.github.com/tsokolowski/73be07589522af7da2bdbfa243f1dd47

**Comment by umila2** [comment]
Sketch: https://editor.p5js.org/usingh/full/SyHCzDQlE
Blog: https://usinghdata.wordpress.com/2018/12/16/life-expectancy-part-1/

**Comment by joeyklee** [comment]
Submissions closed

**Comment by looful** [comment]
Sketch: https://editor.p5js.org/looful/full/HJd9SuKlV
Blog: https://www.lucianar.com/blog/all-things-data

**Comment by kubo921118** [comment]
https://editor.p5js.org/kubo921118/sketches/Sy-TXj4gE
