### ISSUE TITLE
 [Assignment] #7: Life Expectancy and More! 

### ISSUE THREAD

**Issue by joeyklee** [sva-dsi/2018-fall-course#19]
Hi All! Please submit the links to your blog posts and visualizations below. 

Link to assignment: https://github.com/sva-dsi/2018-fall-course/blob/master/week07/ASSIGNMENT07.md

Thanks all! 

***

- [x] @zbordenet
- [x] @JishengChen
- [x] @raaycho
- [x] @catalinacipri
- [x] @rutvigupta
- [x] @danihernandezdesign
- [x] @mblumley 
- [x] @zachnarva
- [x] @p7rathi
- [x] @corinnereynolds
- [x] @dshepardL
- [x] @umila2
- [x] @dskinn
- [x] @tsokolowski
- [x] @ytsai2
- [x] @YUWEN95
- [x] @xialibabanan
- [x] @jdong5

## Missing
- [ ] @wenqizheng
- [ ] @looful
- [ ] @kubo921118
- [ ] @jpanicola
- [ ] @loveisthemssg

**Comment by catalinacipri** [comment]
https://gist.github.com/catalinacipri/c36c81f6df3473bc2d2e68761dd97aaf

**Comment by dshepardL** [comment]
http://dsheparddataviz.data.blog/2018/10/24/lets-try-to-build-a-webpage/

**Comment by raaycho** [comment]
https://metricdataviz.tumblr.com/post/179407002804/life-expectancy-website

**Comment by mblumley** [comment]
https://gist.github.com/mblumley/1613e7c7d29a9e57cf2dcd62a72ffda5

**Comment by rutvigupta** [comment]
https://gist.github.com/rutvigupta/0905813e21b236e55c7524c06a86c825

**Comment by danihernandezdesign** [comment]
https://gist.github.com/danihernandezdesign/9783eaa24e8a720b6efc3badb10379be

**Comment by corinnereynolds** [comment]
Hereeeeeeeee it is. Thanks!
https://editor.p5js.org/corinnereynolds/sketches/HykI4vpjm

**Comment by dskinn** [comment]
https://editor.p5js.org/dskinn/sketches/HyR5LVt37
A few questions on a blog post: https://gist.github.com/dskinn/90d1318c8d1f1b757818c2014ac8f1e7

**Comment by zbordenet** [comment]
blog: https://wordpress.com/post/zbdatavisualization.wordpress.com/43
p5: https://editor.p5js.org/zbordenet/sketches/HkcXkuk37

**Comment by xialibabanan** [comment]
p5: https://editor.p5js.org/xzhang9213@gmail.com/sketches/HJ1M5kdaQ
https://editor.p5js.org/xzhang9213@gmail.com/full/HJ1M5kdaQ
BLOG: https://xiananzhang.wordpress.com/2018/12/14/data-assignment-7-life-expectancy-and-more/

**Comment by ytsai2** [comment]
p5: https://editor.p5js.org/dataviz.yt/sketches/B12TbSQyV

**Comment by JishengChen** [comment]
p5: https://editor.p5js.org/jchen56@sva.edu/sketches/BkJSRQzpX

**Comment by zachnarva** [comment]
p5: https://editor.p5js.org/znarva/sketches/SJxZjvbfpm

**Comment by YUWEN95** [comment]
p5: https://editor.p5js.org/YUWEN95/sketches/r1wqhaGlV

**Comment by jdong5** [comment]
Visual: https://editor.p5js.org/jdong5/sketches/HkFT90ByE
Blog: https://jaithesis.wordpress.com/2018/11/23/reflection-on-assignment-7-life-expectancy-2/

**Comment by tsokolowski** [comment]
Site: https://editor.p5js.org/tsokolowski/full/HklslAeg4
Blog: https://gist.github.com/tsokolowski/56655735d0e4dcb29e8d0dc2f899cf27

**Comment by umila2** [comment]
p5: https://editor.p5js.org/usingh/sketches/H1i7f9VeE

**Comment by joeyklee** [comment]
Submissions closed

**Comment by looful** [comment]
p5: https://editor.p5js.org/looful/full/rypkvqFl4 
Blog: https://www.lucianar.com/blog/all-things-data

**Comment by ghost** [comment]
https://editor.p5js.org/wenqizheng/sketches/H1Tdau1h7

**Comment by kubo921118** [comment]
https://editor.p5js.org/kubo921118/sketches/8epGYp-g7
