### ISSUE TITLE
[Assignment] #1.1 - Links to Github Repo, your first Gist, and Moodboard

### ISSUE THREAD

**Issue by joeyklee** [sva-dsi/2018-fall-course#2]
**Please submit part 1.1 of [week 1's assignment](https://github.com/sva-dsi/2018-fall-course/blob/master/week01/ASSIGNMENT01.md) below.** 

## Note:
- See my comment below as an example of how you might post the links to part 1.1 of the assignment 

## Make sure to submit:
  - [x] Your Github Repo
  - [x] Your Gist
  - [x] Your Moodboard for SVA DSI

***

- [x] @zbordenet
- [x] @JishengChen
- [x] @raaycho
- [x] @catalinacipri
- [x] @rutvigupta
- [x] @danihernandezdesign
- [x] @mblumley
- [x] @loveisthemssg
- [x] @zachnarva
- [x] @jpanicola
- [x] @p7rathi
- [x] @corinnereynolds
- [x] @dshepardL
- [x] @umila2
- [x] @dskinn
- [x] @tsokolowski
- [x] @ytsai2
- [x] @kubo921118
- [x] @YUWEN95
- [x] @xialibabanan
- [x] @wenqizheng
- [x] @looful
- [x] @jdong5

**Comment by joeyklee** [comment]
## Joey Lee

- Github Repo URL: https://github.com/joeyklee/dsi-dataviz-1 
- My First Gist URL: https://gist.github.com/joeyklee/f2ab8d2526b2d45ecbae97886743a6e8
- My Moodboard URL: https://www.pinterest.com/josephkanglee/sva-dataviz/

**Comment by danihernandezdesign** [comment]
Github Repo URL: https://github.com/danihernandezdesign/dataviz1
My First Gist URL: https://gist.github.com/danihernandezdesign/76def8ce8b3f59f53bc62c72a97eea8b
My Moodboard URL: https://www.pinterest.com/danichanh/infographics/

**Comment by catalinacipri** [comment]
**Github Repo**
https://github.com/catalinacipri/dsi-datavis-1/

**Gist URL:**
 https://gist.github.com/catalinacipri/0d9d107d1e2ddada2431aaf364a8a419

**Moodboard URL:** 
https://pin.it/thgfoy5a6gjjix

**Comment by zachnarva** [comment]
**Repo:**

**Gist:** https://gist.github.com/zachnarva/5c7a1e42d891e9f69171727f3ac0f2c9

**Moodboard:** https://www.pinterest.com/zachnarvaDSI/

**Comment by wenqizheng** [comment]
**Github Repo**: https://github.com/wenqizheng/dsi-datavis-1
**My First Gist**: https://gist.github.com/wenqizheng/cf517e23fb831dc7f560dce3a0a6ef20
**My Moodboard URL**: https://www.pinterest.jp/wzheng527/sva-dsi-dataviz/

**Comment by dshepardL** [comment]
Github Repo: [](https://github.com/dshepardL/DanielleShepard)
My First Gist: <script src="https://gist.github.com/dshepardL/2e8d6bfc9b8b0b37432ad5d02e4fdfee.js"></script>
Moodboard: https://pin.it/kubm3rboibsslg

**Comment by dshepardL** [comment]
Repo: https://github.com/dshepardL/DanielleShepard#danielleshepard
Gist: https://gist.github.com/dshepardL/2e8d6bfc9b8b0b37432ad5d02e4fdfee
Moodboard: https://pin.it/h2lznukeeaigqc

**Comment by rutvigupta** [comment]
**Githib Repo:** https://github.com/rutvigupta/dsi-datavis-1

**My First GIST (woohoo):** https://gist.github.com/rutvigupta/a8488e7674197d8cb95f3c0bd798294b

**Moodboard:** https://www.pinterest.com/rpgupta2/sva-dataviz/

**Comment by umila2** [comment]
Umila Singh:
Repo: https://github.com/umila2/my_first_repo
Gist: https://gist.github.com/umila2/32b3fa67308757fe901046903a07d059#file-test-md
Moodboard: https://pin.it/mn6ly3pvmw6iht

**Comment by tsokolowski** [comment]
**Taylor Sokolowski**
Github Repo: https://github.com/tsokolowski/dsi-dataviz-1
My First Gist: https://gist.github.com/tsokolowski/fd96c1ea21e40ecb9336c6595f4545e0
My Moodboard: https://www.pinterest.cl/tsokolowski1/sva-dataviz/

**Comment by ytsai2** [comment]
Github Repo: https://github.com/ytsai2/dsi-datavis-1
My First Gist: https://gist.github.com/ytsai2
My Moodboard: https://www.pinterest.com/ytsai2/dsi-dataviz/

**Comment by dskinn** [comment]
https://github.com/dskinn/datavizrookie
https://gist.github.com/dskinn/ce8255052686b055e81ee4416a0120c4
https://www.pinterest.com/dnleskn/maps/

**Comment by raaycho** [comment]
Github Repo: https://github.com/raaycho/datavis_091318/blob/master/README.md
Gist: https://gist.github.com/raaycho/76fb955cc9b8aa4158bdab3de31bd8fe
Moodboard: https://www.pinterest.com/raaycho6793/moodboard_data-vis-i/

**Comment by zbordenet** [comment]
Github repo: https://github.com/zbordenet/dsi-datavis-1
Gist: https://gist.github.com/zbordenet/01e1a8b7e72b33f677202596aea881ac
Moodboard: https://www.pinterest.com/zoebordenet/sva-dataviz/

**Comment by YUWEN95** [comment]
Github repo: https://github.com/YUWEN95?tab=repositories
Gist: https://gist.github.com/YUWEN95
Moodboard: https://www.pinterest.com/ywang101/sva-dataviz/

**Comment by corinnereynolds** [comment]
Github repo: https://github.com/corinnereynolds/dsi-dataviz
Gist: https://gist.github.com/corinnereynolds/
Moodboard: https://www.pinterest.com/coco2930/data-visualizations/

**Comment by kubo921118** [comment]
Github repo: https://github.com/kubo921118/dsi-datavis-kubo
Gist: https://gist.github.com/kubo921118/2804368a6d90f61cf0a06fdc2bd1233f
Moodboard: https://www.pinterest.com/xujun1845/sva-dataviz/

**Comment by p7rathi** [comment]
Github repo: https://github.com/p7rathi/dsi-datavis-1
Gist: https://gist.github.com/p7rathi/f0ff0bb0d37cda066dd0dc54315f914a
Moodboard: https://www.pinterest.cl/pratiksharathi1/sva-dataviz/

**Comment by JishengChen** [comment]
Github repo:https://github.com/JishengChen/dsi-datavis-1
Gist:https://gist.github.com/JishengChen
Moodboard:https://www.pinterest.com/jchen56/sparkles-for-dataviz/

**Comment by mblumley** [comment]
Github Repo URL: https://github.com/mblumley/dsi-datavis-1
My First Gist URL: https://gist.github.com/mblumley/c025a93142912dfdadf1e67b5e79641d
My Moodboard URL: https://www.pinterest.com/mlumley8365/sva-dataviz/

**Comment by loveisthemssg** [comment]
Repo: https://github.com/loveisthemssg/dsi-datavis-1
Gist: https://gist.github.com/loveisthemssg/49fc915f86c0c7f92cfd7519ab2555a3#file-markdown-syntax-practice-md
Moodboard: https://www.pinterest.com/jmorse3223/sva-dataviz/

**Comment by xialibabanan** [comment]
Repo:https://github.com/xialibabanan/1.1/edit/master/README.md
Gist:https://gist.github.com/xialibabanan/a15b64cd8fda92eb86bbc6a4a9016d6f
Moodboard:https://www.pinterest.com/xiananzhang7/data-visualisation/

**Comment by jdong5** [comment]
Github Repo: https://github.com/jdong5/dsi-datavis-1
My First Gist: https://gist.github.com/jdong5/813f5b4f240e5d411a40648ef87a7df2
My Moodboard: https://www.pinterest.com/etkt950108/sva-dataviz/

**Comment by joeyklee** [comment]
@looful

Assignment 1:
Blog Post: https://www.lucianar.com/blog/2018/10/30/all-things-data

Repo: https://github.com/looful/data-viz-1
Gist: https://gist.github.com/looful/d64227e995600dcb2e718b8a05612ddf
Moodboard: https://pin.it/kbrixehfv7ew6c

**Comment by joeyklee** [comment]
Closing this issue / Submissions
