### ISSUE TITLE
Account Flagged?

### ISSUE THREAD

**Issue by rutvigupta** [sva-dsi/2018-fall-course#5]
Hey Joey! My account got flagged for some reason, and I've contact support, but has this happened to you in the past? Not too sure what I ended up doing!

**Comment by joeyklee** [comment]
Hi @rutvigupta oh no! Strange. Not sure why this would happen. Let me know if this gets resolved and/or if I can help in any way!

**Comment by rutvigupta** [comment]
@joeyklee thanks - all resolved!

**Comment by joeyklee** [comment]
Super! 🌴 will close this issue now :)
